TrajectoryPlannerROS:
  max_vel_x: 4.0
  min_vel_x: 0.1
  max_vel_theta: 3.0
  min_in_place_vel_theta: 1.0
  escape_vel : -0.5

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  pdist_scale : 1.5
  gdist_scale : 1.0
    
  sim_time : 2.0
  yaw_goal_tolerance : 0.05
  xy_goal_tolerance : 0.05
  holonomic_robot: false
